# Generated by Django 2.1.7 on 2019-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190306_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('created_modified', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyEmp',
        ),
    ]
