# Generated by Django 2.1.7 on 2019-03-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190306_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('date_time', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('created_modified', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='todoItem',
        ),
    ]
