# Generated by Django 2.1.7 on 2019-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190307_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem1',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
