# Generated by Django 2.1.7 on 2019-03-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190307_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem1',
            old_name='title',
            new_name='Title',
        ),
    ]
