# Generated by Django 2.1.7 on 2019-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190307_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem1',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem1',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
