# Generated by Django 2.1.7 on 2019-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190307_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem1',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
