# Generated by Django 2.1.7 on 2019-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190307_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem1',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
