# Generated by Django 2.1.7 on 2019-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190307_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem1',
            name='created_modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
